# Example YAML to get you started quickly.
# Be aware that YAML has indentation based scoping.
# Code completion support is available so start typing for available options.
swagger: '2.0'

# This is your document metadata
info:
  version: "0.0.1"
  title: voting app
host:
  http://35.167.112.139:3000
# Describe your paths here
paths:
  # This is a path endpoint. Change it.
  /votes/{id}:
    # This is a HTTP operation
    get:
      description: Returns a user based on a single ID, if the user does not have access to the pet
      operationId: findVoteById
      produces:
        - application/json
        - application/xml
        - text/xml
        - text/html
      parameters:
        - name: id
          in: path
          description: ID of vote to fetch
          required: true
          type: integer
          format: int64 
      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: Successful response
          # A schema describing your response object.
          # Use JSON Schema format
          schema:
            title: ArrayOfVotes
            type: array
            items:
              title: Vote
              type: object
              properties:
                name:
                  type: string
                value:
                  type: string
    # This is a HTTP operation
    delete:
      description: deletes a single vote based on the ID supplied
      operationId: deleteVoteById
      parameters:
        - name: id
          in: path
          description: ID of vote to delete
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
          # Use JSON Schema format
          schema:
            title: DeleteOfVotes
            type: array
            items:
              title: Vote
              type: object
              properties:
                name:
                  type: string
        204:
          description: vote deleted
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
definitions:
  errorModel:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
